locals {
  deployment_policy_name = {
    for environment in local.environments :
    environment => "${environment}-health-check-deployment-policy"
  }
}

data "aws_iam_policy_document" "deployment" {
  for_each = local.environments

  statement {
    sid    = "ReadOwnStateBucket"
    effect = "Allow"
    actions = [
      "s3:GetBucketLocation",
      "s3:GetBucketVersioning",
    ]
    resources = [local.state_bucket_arn]
  }

  statement {
    sid     = "ListOwnStatePrefix"
    effect  = "Allow"
    actions = ["s3:ListBucket"]
    resources = [local.state_bucket_arn]

    condition {
      test     = "StringLike"
      variable = "s3:prefix"
      values = [
        local.state_key_by_environment[each.key],
        "${local.state_key_by_environment[each.key]}.tflock",
      ]
    }
  }

  statement {
    sid    = "ManageOwnStateObjects"
    effect = "Allow"
    actions = [
      "s3:DeleteObject",
      "s3:GetObject",
      "s3:PutObject",
    ]
    resources = [
      "${local.state_bucket_arn}/${local.state_key_by_environment[each.key]}",
      "${local.state_bucket_arn}/${local.state_key_by_environment[each.key]}.tflock",
    ]
  }

  statement {
    sid    = "UseStateEncryptionKey"
    effect = "Allow"
    actions = [
      "kms:Decrypt",
      "kms:DescribeKey",
      "kms:Encrypt",
      "kms:GenerateDataKey",
    ]
    resources = [aws_kms_key.state.arn]
  }

  statement {
    sid    = "ManageExactRuntimeRole"
    effect = "Allow"
    actions = [
      "iam:CreateRole",
      "iam:DeleteRole",
      "iam:GetRole",
      "iam:ListRolePolicies",
      "iam:TagRole",
      "iam:UntagRole",
      "iam:UpdateAssumeRolePolicy",
    ]
    resources = [local.resource_arns[each.key].runtime_role]
  }

  statement {
    sid    = "ManageExactRuntimeInlinePolicy"
    effect = "Allow"
    actions = [
      "iam:DeleteRolePolicy",
      "iam:GetRolePolicy",
      "iam:PutRolePolicy",
    ]
    resources = [local.resource_arns[each.key].runtime_role]
  }

  statement {
    sid       = "PassRuntimeRoleOnlyToLambda"
    effect    = "Allow"
    actions   = ["iam:PassRole"]
    resources = [local.resource_arns[each.key].runtime_role]

    condition {
      test     = "StringEquals"
      variable = "iam:PassedToService"
      values   = ["lambda.amazonaws.com"]
    }
  }

  statement {
    sid    = "ManageExactLambda"
    effect = "Allow"
    actions = [
      "lambda:AddPermission",
      "lambda:CreateFunction",
      "lambda:DeleteFunction",
      "lambda:DeleteFunctionConcurrency",
      "lambda:GetFunction",
      "lambda:GetFunctionCodeSigningConfig",
      "lambda:GetFunctionConfiguration",
      "lambda:GetPolicy",
      "lambda:GetRuntimeManagementConfig",
      "lambda:ListTags",
      "lambda:ListVersionsByFunction",
      "lambda:PutFunctionConcurrency",
      "lambda:PutRuntimeManagementConfig",
      "lambda:RemovePermission",
      "lambda:TagResource",
      "lambda:UntagResource",
      "lambda:UpdateFunctionCode",
      "lambda:UpdateFunctionConfiguration",
    ]
    resources = [local.resource_arns[each.key].function]
  }

  statement {
    sid    = "ManageExactDynamoDBTable"
    effect = "Allow"
    actions = [
      "dynamodb:CreateTable",
      "dynamodb:DeleteTable",
      "dynamodb:DescribeContinuousBackups",
      "dynamodb:DescribeTable",
      "dynamodb:DescribeTimeToLive",
      "dynamodb:ListTagsOfResource",
      "dynamodb:TagResource",
      "dynamodb:UntagResource",
      "dynamodb:UpdateContinuousBackups",
      "dynamodb:UpdateTable",
      "dynamodb:UpdateTimeToLive",
    ]
    resources = [local.resource_arns[each.key].table]
  }

  # kms:CreateKey has no resource-level authorization because the key does not
  # exist yet. Conditions bind creation to this project/environment and key type.
  statement {
    sid       = "CreateOnlyApplicationEncryptionKey"
    effect    = "Allow"
    actions   = ["kms:CreateKey"]
    resources = ["*"]

    condition {
      test     = "StringEquals"
      variable = "kms:KeySpec"
      values   = ["SYMMETRIC_DEFAULT"]
    }

    condition {
      test     = "StringEquals"
      variable = "kms:KeyUsage"
      values   = ["ENCRYPT_DECRYPT"]
    }

    condition {
      test     = "Bool"
      variable = "kms:MultiRegion"
      values   = ["false"]
    }

    condition {
      test     = "StringEquals"
      variable = "aws:RequestTag/Environment"
      values   = [each.key]
    }

    condition {
      test     = "StringEquals"
      variable = "aws:RequestTag/Project"
      values   = [local.project_name]
    }
  }

  # Key IDs are generated by AWS. Resource tags constrain management to the key
  # created for this environment; the KMS key policy provides an additional gate.
  statement {
    sid    = "ManageTaggedApplicationEncryptionKey"
    effect = "Allow"
    actions = [
      "kms:CancelKeyDeletion",
      "kms:DescribeKey",
      "kms:DisableKey",
      "kms:DisableKeyRotation",
      "kms:EnableKey",
      "kms:EnableKeyRotation",
      "kms:GetKeyPolicy",
      "kms:GetKeyRotationStatus",
      "kms:ListGrants",
      "kms:ListResourceTags",
      "kms:PutKeyPolicy",
      "kms:RevokeGrant",
      "kms:ScheduleKeyDeletion",
      "kms:TagResource",
      "kms:UntagResource",
      "kms:UpdateKeyDescription",
    ]
    resources = [local.resource_arns[each.key].application_key]

    condition {
      test     = "StringEquals"
      variable = "aws:ResourceTag/Environment"
      values   = [each.key]
    }

    condition {
      test     = "StringEquals"
      variable = "aws:ResourceTag/Project"
      values   = [local.project_name]
    }
  }

  statement {
    sid    = "ManageExactApplicationKeyAlias"
    effect = "Allow"
    actions = [
      "kms:CreateAlias",
      "kms:DeleteAlias",
      "kms:UpdateAlias",
    ]
    resources = [
      local.resource_arns[each.key].application_key_alias,
      local.resource_arns[each.key].application_key,
    ]
  }

  # KMS ListAliases does not support resource-level authorization.
  statement {
    sid       = "DiscoverKmsAliases"
    effect    = "Allow"
    actions   = ["kms:ListAliases"]
    resources = ["*"]
  }

  # EC2 Describe APIs used by the Terraform provider do not support resource-level
  # authorization. RequestedRegion prevents cross-region discovery.
  statement {
    sid    = "DescribeRegionalEc2ControlPlane"
    effect = "Allow"
    actions = [
      "ec2:DescribeAvailabilityZones",
      "ec2:DescribeManagedPrefixLists",
      "ec2:DescribeNetworkInterfaces",
      "ec2:DescribePrefixLists",
      "ec2:DescribeRouteTables",
      "ec2:DescribeSecurityGroupRules",
      "ec2:DescribeSecurityGroups",
      "ec2:DescribeSubnets",
      "ec2:DescribeTags",
      "ec2:DescribeVpcAttribute",
      "ec2:DescribeVpcEndpoints",
      "ec2:DescribeVpcs",
    ]
    resources = ["*"]

    condition {
      test     = "StringEquals"
      variable = "aws:RequestedRegion"
      values   = [var.aws_region]
    }
  }

  # AWS generates EC2 resource IDs. Restrict creates using mandatory project and
  # environment request tags, then restrict later mutations using resource tags.
  statement {
    sid    = "CreateTaggedApplicationNetwork"
    effect = "Allow"
    actions = [
      "ec2:CreateRouteTable",
      "ec2:CreateSecurityGroup",
      "ec2:CreateSubnet",
      "ec2:CreateVpc",
      "ec2:CreateVpcEndpoint",
    ]
    resources = ["*"]

    condition {
      test     = "StringEquals"
      variable = "aws:RequestTag/Environment"
      values   = [each.key]
    }

    condition {
      test     = "StringEquals"
      variable = "aws:RequestTag/Project"
      values   = [local.project_name]
    }
  }

  statement {
    sid    = "ManageTaggedApplicationNetwork"
    effect = "Allow"
    actions = [
      "ec2:AssociateRouteTable",
      "ec2:AuthorizeSecurityGroupEgress",
      "ec2:CreateTags",
      "ec2:DeleteRouteTable",
      "ec2:DeleteSecurityGroup",
      "ec2:DeleteSubnet",
      "ec2:DeleteTags",
      "ec2:DeleteVpc",
      "ec2:DeleteVpcEndpoints",
      "ec2:DisassociateRouteTable",
      "ec2:ModifyVpcAttribute",
      "ec2:ModifyVpcEndpoint",
      "ec2:RevokeSecurityGroupEgress",
    ]
    resources = [
      local.resource_arns[each.key].ec2_vpcs,
      local.resource_arns[each.key].ec2_subnets,
      local.resource_arns[each.key].ec2_route_tables,
      local.resource_arns[each.key].ec2_security_group,
      local.resource_arns[each.key].ec2_vpc_endpoint,
    ]

    condition {
      test     = "StringEquals"
      variable = "aws:ResourceTag/Environment"
      values   = [each.key]
    }

    condition {
      test     = "StringEquals"
      variable = "aws:ResourceTag/Project"
      values   = [local.project_name]
    }
  }

  # API Gateway assigns REST API, API key, model, validator, deployment and usage
  # plan IDs at creation. Paths are constrained to this region and only the API
  # Gateway resource families needed by this stack.
  statement {
    sid    = "ManageHealthCheckApiGateway"
    effect = "Allow"
    actions = [
      "apigateway:DELETE",
      "apigateway:GET",
      "apigateway:PATCH",
      "apigateway:POST",
      "apigateway:PUT",
    ]
    resources = local.resource_arns[each.key].api_gateway
  }

  statement {
    sid    = "ManageApplicationLogGroups"
    effect = "Allow"
    actions = [
      "logs:CreateLogGroup",
      "logs:DeleteLogGroup",
      "logs:DeleteRetentionPolicy",
      "logs:ListTagsForResource",
      "logs:PutRetentionPolicy",
      "logs:TagResource",
      "logs:UntagResource",
    ]
    resources = local.resource_arns[each.key].log_groups
  }

  # DescribeLogGroups is a list API and requires Resource "*".
  statement {
    sid       = "DiscoverRegionalLogGroups"
    effect    = "Allow"
    actions   = ["logs:DescribeLogGroups"]
    resources = ["*"]

    condition {
      test     = "StringEquals"
      variable = "aws:RequestedRegion"
      values   = [var.aws_region]
    }
  }

  statement {
    sid    = "ManageExactCloudWatchAlarms"
    effect = "Allow"
    actions = [
      "cloudwatch:DeleteAlarms",
      "cloudwatch:DescribeAlarms",
      "cloudwatch:ListTagsForResource",
      "cloudwatch:PutMetricAlarm",
      "cloudwatch:TagResource",
      "cloudwatch:UntagResource",
    ]
    resources = local.resource_arns[each.key].alarms
  }

  statement {
    sid    = "ManageExactDashboard"
    effect = "Allow"
    actions = [
      "cloudwatch:DeleteDashboards",
      "cloudwatch:GetDashboard",
      "cloudwatch:PutDashboard",
    ]
    resources = [local.resource_arns[each.key].dashboard]
  }
}

resource "aws_iam_role_policy" "deployment" {
  for_each = local.environments

  name   = local.deployment_policy_name[each.key]
  role   = aws_iam_role.deployment[each.key].id
  policy = data.aws_iam_policy_document.deployment[each.key].json
}
