version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    labels:
      - dependencies

  - package-ecosystem: pip
    directory: "/lambda"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - python

  - package-ecosystem: terraform
    directory: "/terraform"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - terraform

  - package-ecosystem: terraform
    directory: "/bootstrap"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - terraform
